=== eumermondio/ejerciciosLMSGI/DTD con errores/Ejercicio02DTD.dtd
<!ELEMENT musica (artistas, canciones, nacionalidades)*>

<!ELEMENT artistas (artista)*>
<!ELEMENT canciones (cancion)*>
<!ELEMENT nacionalidades (nacionalidad)*>

<!ELEMENT artista EMPTY>
<!ELEMENT cancion EMPTY>
<!ELEMENT nacionalidad (#PCDATA)>

<!ATTLIST artista nombre ID #REQUIRED
                    fechaNacimiento CDATA #REQUIRED
                    nacionalidad IDREF #REQUIRED>
<!ATTLIST cancion nombre NMTOKENS #REQUIRED
                    duracion CDATA #REQUIRED
                    artista IDREF #REQUIRED>
<!ATTLIST nacionalidad codigo ID #REQUIRED>

=== eumermondio/ejerciciosLMSGI/Ejercicio02XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musica SYSTEM "Ejercicio02DTD.dtd">

<musica>
    <artistas>
        <artista nombre="Pepe" fechaNacimiento="1978" nacionalidad="ES" />
        <artista nombre="Antonio" fechaNacimiento="1980" nacionalidad="FR" />
    </artistas>
    <canciones>
        <cancion nombre="Dos" duracion="34" artista="Pepe" />
        <cancion nombre="Tres" duracion="31" artista="Antonio" />
    </canciones>
    <nacionalidades>
        <nacionalidad codigo="ES">Espa√±ola</nacionalidad>
        <nacionalidad codigo="FR">Francesa</nacionalidad>
    </nacionalidades>
</musica>
