=== eumermondio/ejerciciosLMSGI/DTD/DTD con errores/monstruos.dtd
<!ENTITY % reqcdata "CDATA #REQUIRED">

<!ELEMENT monstruos (monstruo | episodios)+>
<!ELEMENT monstruo (#PCDATA | tipo | caracteristicas)*>
<!ATTLIST monstruo cod ID #REQUIRED>
<!ATTLIST monstruo episodios IDREFS #REQUIRED>
<!ATTLIST monstruo amigo IDREF #REQUIRED>


<!ELEMENT episodios (continuado | descontinuado)>
<!ATTLIST episodios codE ID #IMPLIED>

<!ELEMENT continuado EMPTY>
<!ELEMENT descontinuado EMPTY>


<!ELEMENT tipo EMPTY>
<!ELEMENT caracteristicas (vida | escudo)?>
<!ELEMENT vida EMPTY>
<!ATTLIST vida cantidad %reqcdata;>


<!ELEMENT escudo EMPTY>
<!ATTLIST escudo vidaEscudo %reqcdata;>
<!ATTLIST escudo tieneEscudo CDATA #FIXED "si">
<!ATTLIST escudo loUsa (si | no | noSeSabe) "si">

=== eumermondio/ejerciciosLMSGI/DTD con errores/monstruos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE monstruos SYSTEM "monstruos.dtd">
<monstruos>

    <monstruo cod="uno" episodios="eptres epuno" amigo="dos">
        monstruo1
        <tipo />
        <caracteristicas>
            <escudo tieneEscudo="si" vidaEscudo="13000" loUsa="noSeSabe"/>
        </caracteristicas>
    </monstruo>

    <monstruo cod="dos" episodios="epdos" amigo="uno">
        monstruo2
        <caracteristicas>
            <vida cantidad="847356"/>
        </caracteristicas>
    </monstruo>

    <episodios codE="epuno">
        <continuado />
    </episodios>

    <episodios codE="epdos">
        <descontinuado />
    </episodios>

    <episodios codE="eptres">
        <continuado />
    </episodios>

</monstruos>
